/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConfigurationSelection from './ConfigurationSelection';

/**
 * The ConfigurationGetConfigurationFromSelectionsRequest model module.
 * @module model/ConfigurationGetConfigurationFromSelectionsRequest
 * @version v1
 */
class ConfigurationGetConfigurationFromSelectionsRequest {
    /**
     * Constructs a new <code>ConfigurationGetConfigurationFromSelectionsRequest</code>.
     * @alias module:model/ConfigurationGetConfigurationFromSelectionsRequest
     */
    constructor() { 
        
        ConfigurationGetConfigurationFromSelectionsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigurationGetConfigurationFromSelectionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigurationGetConfigurationFromSelectionsRequest} obj Optional instance to populate.
     * @return {module:model/ConfigurationGetConfigurationFromSelectionsRequest} The populated <code>ConfigurationGetConfigurationFromSelectionsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigurationGetConfigurationFromSelectionsRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('selections')) {
                obj['selections'] = ApiClient.convertToType(data['selections'], [ConfigurationSelection]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigurationGetConfigurationFromSelectionsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigurationGetConfigurationFromSelectionsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['productId'] && !(typeof data['productId'] === 'string' || data['productId'] instanceof String)) {
            throw new Error("Expected the field `productId` to be a primitive type in the JSON string but got " + data['productId']);
        }
        if (data['selections']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['selections'])) {
                throw new Error("Expected the field `selections` to be an array in the JSON data but got " + data['selections']);
            }
            // validate the optional field `selections` (array)
            for (const item of data['selections']) {
                ConfigurationSelection.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
ConfigurationGetConfigurationFromSelectionsRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} productId
 */
ConfigurationGetConfigurationFromSelectionsRequest.prototype['productId'] = undefined;

/**
 * @member {Array.<module:model/ConfigurationSelection>} selections
 */
ConfigurationGetConfigurationFromSelectionsRequest.prototype['selections'] = undefined;






export default ConfigurationGetConfigurationFromSelectionsRequest;

