/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConfigurationConfigurationStep from './ConfigurationConfigurationStep';
import ConfigurationProperty from './ConfigurationProperty';

/**
 * The ConfigurationGetConfigurationFromSelectionsResponse model module.
 * @module model/ConfigurationGetConfigurationFromSelectionsResponse
 * @version v1
 */
class ConfigurationGetConfigurationFromSelectionsResponse {
    /**
     * Constructs a new <code>ConfigurationGetConfigurationFromSelectionsResponse</code>.
     * @alias module:model/ConfigurationGetConfigurationFromSelectionsResponse
     */
    constructor() { 
        
        ConfigurationGetConfigurationFromSelectionsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigurationGetConfigurationFromSelectionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigurationGetConfigurationFromSelectionsResponse} obj Optional instance to populate.
     * @return {module:model/ConfigurationGetConfigurationFromSelectionsResponse} The populated <code>ConfigurationGetConfigurationFromSelectionsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigurationGetConfigurationFromSelectionsResponse();

            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [ConfigurationConfigurationStep]);
            }
            if (data.hasOwnProperty('matchedProperties')) {
                obj['matchedProperties'] = ApiClient.convertToType(data['matchedProperties'], [ConfigurationProperty]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigurationGetConfigurationFromSelectionsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigurationGetConfigurationFromSelectionsResponse</code>.
     */
    static validateJSON(data) {
        if (data['steps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['steps'])) {
                throw new Error("Expected the field `steps` to be an array in the JSON data but got " + data['steps']);
            }
            // validate the optional field `steps` (array)
            for (const item of data['steps']) {
                ConfigurationConfigurationStep.validateJSON(item);
            };
        }
        if (data['matchedProperties']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matchedProperties'])) {
                throw new Error("Expected the field `matchedProperties` to be an array in the JSON data but got " + data['matchedProperties']);
            }
            // validate the optional field `matchedProperties` (array)
            for (const item of data['matchedProperties']) {
                ConfigurationProperty.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ConfigurationConfigurationStep>} steps
 */
ConfigurationGetConfigurationFromSelectionsResponse.prototype['steps'] = undefined;

/**
 * @member {Array.<module:model/ConfigurationProperty>} matchedProperties
 */
ConfigurationGetConfigurationFromSelectionsResponse.prototype['matchedProperties'] = undefined;






export default ConfigurationGetConfigurationFromSelectionsResponse;

