/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorconfigurationStep from './ProductconfiguratorconfigurationStep';

/**
 * The ConfigurationConfigurator model module.
 * @module model/ConfigurationConfigurator
 * @version v1
 */
class ConfigurationConfigurator {
    /**
     * Constructs a new <code>ConfigurationConfigurator</code>.
     * @alias module:model/ConfigurationConfigurator
     */
    constructor() { 
        
        ConfigurationConfigurator.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigurationConfigurator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigurationConfigurator} obj Optional instance to populate.
     * @return {module:model/ConfigurationConfigurator} The populated <code>ConfigurationConfigurator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigurationConfigurator();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('grn')) {
                obj['grn'] = ApiClient.convertToType(data['grn'], 'String');
            }
            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [ProductconfiguratorconfigurationStep]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigurationConfigurator</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigurationConfigurator</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['grn'] && !(typeof data['grn'] === 'string' || data['grn'] instanceof String)) {
            throw new Error("Expected the field `grn` to be a primitive type in the JSON string but got " + data['grn']);
        }
        if (data['steps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['steps'])) {
                throw new Error("Expected the field `steps` to be an array in the JSON data but got " + data['steps']);
            }
            // validate the optional field `steps` (array)
            for (const item of data['steps']) {
                ProductconfiguratorconfigurationStep.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ConfigurationConfigurator.prototype['id'] = undefined;

/**
 * @member {String} grn
 */
ConfigurationConfigurator.prototype['grn'] = undefined;

/**
 * @member {Array.<module:model/ProductconfiguratorconfigurationStep>} steps
 */
ConfigurationConfigurator.prototype['steps'] = undefined;






export default ConfigurationConfigurator;

