/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConfigurationStepOption from './ConfigurationStepOption';
import LocalisationLocalizedText from './LocalisationLocalizedText';

/**
 * The ConfigurationConfigurationStep model module.
 * @module model/ConfigurationConfigurationStep
 * @version v1
 */
class ConfigurationConfigurationStep {
    /**
     * Constructs a new <code>ConfigurationConfigurationStep</code>.
     * @alias module:model/ConfigurationConfigurationStep
     */
    constructor() { 
        
        ConfigurationConfigurationStep.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigurationConfigurationStep</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigurationConfigurationStep} obj Optional instance to populate.
     * @return {module:model/ConfigurationConfigurationStep} The populated <code>ConfigurationConfigurationStep</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigurationConfigurationStep();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('grn')) {
                obj['grn'] = ApiClient.convertToType(data['grn'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = LocalisationLocalizedText.constructFromObject(data['label']);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [ConfigurationStepOption]);
            }
            if (data.hasOwnProperty('hasMultipleSelection')) {
                obj['hasMultipleSelection'] = ApiClient.convertToType(data['hasMultipleSelection'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigurationConfigurationStep</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigurationConfigurationStep</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['grn'] && !(typeof data['grn'] === 'string' || data['grn'] instanceof String)) {
            throw new Error("Expected the field `grn` to be a primitive type in the JSON string but got " + data['grn']);
        }
        // validate the optional field `label`
        if (data['label']) { // data not null
          LocalisationLocalizedText.validateJSON(data['label']);
        }
        if (data['options']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['options'])) {
                throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
            }
            // validate the optional field `options` (array)
            for (const item of data['options']) {
                ConfigurationStepOption.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ConfigurationConfigurationStep.prototype['id'] = undefined;

/**
 * @member {String} grn
 */
ConfigurationConfigurationStep.prototype['grn'] = undefined;

/**
 * @member {module:model/LocalisationLocalizedText} label
 */
ConfigurationConfigurationStep.prototype['label'] = undefined;

/**
 * @member {Array.<module:model/ConfigurationStepOption>} options
 */
ConfigurationConfigurationStep.prototype['options'] = undefined;

/**
 * @member {Boolean} hasMultipleSelection
 */
ConfigurationConfigurationStep.prototype['hasMultipleSelection'] = undefined;






export default ConfigurationConfigurationStep;

