/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConfigurationOptionProperty from './ConfigurationOptionProperty';
import LocalisationLocalizedText from './LocalisationLocalizedText';
import OptionSwatch from './OptionSwatch';

/**
 * The ConfigurationStepOption model module.
 * @module model/ConfigurationStepOption
 * @version v1
 */
class ConfigurationStepOption {
    /**
     * Constructs a new <code>ConfigurationStepOption</code>.
     * @alias module:model/ConfigurationStepOption
     */
    constructor() { 
        
        ConfigurationStepOption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigurationStepOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigurationStepOption} obj Optional instance to populate.
     * @return {module:model/ConfigurationStepOption} The populated <code>ConfigurationStepOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigurationStepOption();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('grn')) {
                obj['grn'] = ApiClient.convertToType(data['grn'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = LocalisationLocalizedText.constructFromObject(data['label']);
            }
            if (data.hasOwnProperty('swatch')) {
                obj['swatch'] = OptionSwatch.constructFromObject(data['swatch']);
            }
            if (data.hasOwnProperty('optionProperties')) {
                obj['optionProperties'] = ApiClient.convertToType(data['optionProperties'], [ConfigurationOptionProperty]);
            }
            if (data.hasOwnProperty('hasQuantity')) {
                obj['hasQuantity'] = ApiClient.convertToType(data['hasQuantity'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigurationStepOption</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigurationStepOption</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['grn'] && !(typeof data['grn'] === 'string' || data['grn'] instanceof String)) {
            throw new Error("Expected the field `grn` to be a primitive type in the JSON string but got " + data['grn']);
        }
        // validate the optional field `label`
        if (data['label']) { // data not null
          LocalisationLocalizedText.validateJSON(data['label']);
        }
        // validate the optional field `swatch`
        if (data['swatch']) { // data not null
          OptionSwatch.validateJSON(data['swatch']);
        }
        if (data['optionProperties']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['optionProperties'])) {
                throw new Error("Expected the field `optionProperties` to be an array in the JSON data but got " + data['optionProperties']);
            }
            // validate the optional field `optionProperties` (array)
            for (const item of data['optionProperties']) {
                ConfigurationOptionProperty.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ConfigurationStepOption.prototype['id'] = undefined;

/**
 * @member {String} grn
 */
ConfigurationStepOption.prototype['grn'] = undefined;

/**
 * @member {module:model/LocalisationLocalizedText} label
 */
ConfigurationStepOption.prototype['label'] = undefined;

/**
 * @member {module:model/OptionSwatch} swatch
 */
ConfigurationStepOption.prototype['swatch'] = undefined;

/**
 * @member {Array.<module:model/ConfigurationOptionProperty>} optionProperties
 */
ConfigurationStepOption.prototype['optionProperties'] = undefined;

/**
 * @member {Boolean} hasQuantity
 */
ConfigurationStepOption.prototype['hasQuantity'] = undefined;






export default ConfigurationStepOption;

