/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratormatrixEntity from './ProductconfiguratormatrixEntity';

/**
 * The MatrixListMatricesResponse model module.
 * @module model/MatrixListMatricesResponse
 * @version v1
 */
class MatrixListMatricesResponse {
    /**
     * Constructs a new <code>MatrixListMatricesResponse</code>.
     * @alias module:model/MatrixListMatricesResponse
     */
    constructor() { 
        
        MatrixListMatricesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatrixListMatricesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatrixListMatricesResponse} obj Optional instance to populate.
     * @return {module:model/MatrixListMatricesResponse} The populated <code>MatrixListMatricesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatrixListMatricesResponse();

            if (data.hasOwnProperty('matrices')) {
                obj['matrices'] = ApiClient.convertToType(data['matrices'], [ProductconfiguratormatrixEntity]);
            }
            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatrixListMatricesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatrixListMatricesResponse</code>.
     */
    static validateJSON(data) {
        if (data['matrices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matrices'])) {
                throw new Error("Expected the field `matrices` to be an array in the JSON data but got " + data['matrices']);
            }
            // validate the optional field `matrices` (array)
            for (const item of data['matrices']) {
                ProductconfiguratormatrixEntity.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['nextPageToken'] && !(typeof data['nextPageToken'] === 'string' || data['nextPageToken'] instanceof String)) {
            throw new Error("Expected the field `nextPageToken` to be a primitive type in the JSON string but got " + data['nextPageToken']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ProductconfiguratormatrixEntity>} matrices
 */
MatrixListMatricesResponse.prototype['matrices'] = undefined;

/**
 * @member {String} nextPageToken
 */
MatrixListMatricesResponse.prototype['nextPageToken'] = undefined;






export default MatrixListMatricesResponse;

