/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorWeightUnit from './ProductconfiguratorWeightUnit';

/**
 * The MatrixWeightType model module.
 * @module model/MatrixWeightType
 * @version v1
 */
class MatrixWeightType {
    /**
     * Constructs a new <code>MatrixWeightType</code>.
     * @alias module:model/MatrixWeightType
     */
    constructor() { 
        
        MatrixWeightType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatrixWeightType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatrixWeightType} obj Optional instance to populate.
     * @return {module:model/MatrixWeightType} The populated <code>MatrixWeightType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatrixWeightType();

            if (data.hasOwnProperty('weightUnit')) {
                obj['weightUnit'] = ProductconfiguratorWeightUnit.constructFromObject(data['weightUnit']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatrixWeightType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatrixWeightType</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/ProductconfiguratorWeightUnit} weightUnit
 */
MatrixWeightType.prototype['weightUnit'] = undefined;






export default MatrixWeightType;

