/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListMatricesRequestFilter from './ListMatricesRequestFilter';

/**
 * The MatrixListMatricesRequest model module.
 * @module model/MatrixListMatricesRequest
 * @version v1
 */
class MatrixListMatricesRequest {
    /**
     * Constructs a new <code>MatrixListMatricesRequest</code>.
     * @alias module:model/MatrixListMatricesRequest
     */
    constructor() { 
        
        MatrixListMatricesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatrixListMatricesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatrixListMatricesRequest} obj Optional instance to populate.
     * @return {module:model/MatrixListMatricesRequest} The populated <code>MatrixListMatricesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatrixListMatricesRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('configuratorId')) {
                obj['configuratorId'] = ApiClient.convertToType(data['configuratorId'], 'String');
            }
            if (data.hasOwnProperty('filterMask')) {
                obj['filterMask'] = ApiClient.convertToType(data['filterMask'], ['String']);
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ListMatricesRequestFilter.constructFromObject(data['filter']);
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'String');
            }
            if (data.hasOwnProperty('pageToken')) {
                obj['pageToken'] = ApiClient.convertToType(data['pageToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatrixListMatricesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatrixListMatricesRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['configuratorId'] && !(typeof data['configuratorId'] === 'string' || data['configuratorId'] instanceof String)) {
            throw new Error("Expected the field `configuratorId` to be a primitive type in the JSON string but got " + data['configuratorId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['filterMask'])) {
            throw new Error("Expected the field `filterMask` to be an array in the JSON data but got " + data['filterMask']);
        }
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          ListMatricesRequestFilter.validateJSON(data['filter']);
        }
        // ensure the json data is a string
        if (data['pageSize'] && !(typeof data['pageSize'] === 'string' || data['pageSize'] instanceof String)) {
            throw new Error("Expected the field `pageSize` to be a primitive type in the JSON string but got " + data['pageSize']);
        }
        // ensure the json data is a string
        if (data['pageToken'] && !(typeof data['pageToken'] === 'string' || data['pageToken'] instanceof String)) {
            throw new Error("Expected the field `pageToken` to be a primitive type in the JSON string but got " + data['pageToken']);
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
MatrixListMatricesRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} configuratorId
 */
MatrixListMatricesRequest.prototype['configuratorId'] = undefined;

/**
 * @member {Array.<String>} filterMask
 */
MatrixListMatricesRequest.prototype['filterMask'] = undefined;

/**
 * @member {module:model/ListMatricesRequestFilter} filter
 */
MatrixListMatricesRequest.prototype['filter'] = undefined;

/**
 * @member {String} pageSize
 */
MatrixListMatricesRequest.prototype['pageSize'] = undefined;

/**
 * @member {String} pageToken
 */
MatrixListMatricesRequest.prototype['pageToken'] = undefined;






export default MatrixListMatricesRequest;

