/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ProductconfiguratorconfiguratorStatus.
* @enum {}
* @readonly
*/
export default class ProductconfiguratorconfiguratorStatus {
    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    
        /**
         * value: "ACTIVE"
         * @const
         */
        "ACTIVE" = "ACTIVE";

    
        /**
         * value: "DRAFT"
         * @const
         */
        "DRAFT" = "DRAFT";

    
        /**
         * value: "DISABLED"
         * @const
         */
        "DISABLED" = "DISABLED";

    

    /**
    * Returns a <code>ProductconfiguratorconfiguratorStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ProductconfiguratorconfiguratorStatus} The enum <code>ProductconfiguratorconfiguratorStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

