/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LocalisationLocalizedText from './LocalisationLocalizedText';

/**
 * The ProductconfiguratorstepBulkCreateRequestCreateEntity model module.
 * @module model/ProductconfiguratorstepBulkCreateRequestCreateEntity
 * @version v1
 */
class ProductconfiguratorstepBulkCreateRequestCreateEntity {
    /**
     * Constructs a new <code>ProductconfiguratorstepBulkCreateRequestCreateEntity</code>.
     * @alias module:model/ProductconfiguratorstepBulkCreateRequestCreateEntity
     */
    constructor() { 
        
        ProductconfiguratorstepBulkCreateRequestCreateEntity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorstepBulkCreateRequestCreateEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorstepBulkCreateRequestCreateEntity} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorstepBulkCreateRequestCreateEntity} The populated <code>ProductconfiguratorstepBulkCreateRequestCreateEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorstepBulkCreateRequestCreateEntity();

            if (data.hasOwnProperty('label')) {
                obj['label'] = LocalisationLocalizedText.constructFromObject(data['label']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = LocalisationLocalizedText.constructFromObject(data['description']);
            }
            if (data.hasOwnProperty('isRequired')) {
                obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('subjectToStepId')) {
                obj['subjectToStepId'] = ApiClient.convertToType(data['subjectToStepId'], 'String');
            }
            if (data.hasOwnProperty('hasMultipleSelection')) {
                obj['hasMultipleSelection'] = ApiClient.convertToType(data['hasMultipleSelection'], 'Boolean');
            }
            if (data.hasOwnProperty('optionsHaveQuantity')) {
                obj['optionsHaveQuantity'] = ApiClient.convertToType(data['optionsHaveQuantity'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorstepBulkCreateRequestCreateEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorstepBulkCreateRequestCreateEntity</code>.
     */
    static validateJSON(data) {
        // validate the optional field `label`
        if (data['label']) { // data not null
          LocalisationLocalizedText.validateJSON(data['label']);
        }
        // validate the optional field `description`
        if (data['description']) { // data not null
          LocalisationLocalizedText.validateJSON(data['description']);
        }
        // ensure the json data is a string
        if (data['subjectToStepId'] && !(typeof data['subjectToStepId'] === 'string' || data['subjectToStepId'] instanceof String)) {
            throw new Error("Expected the field `subjectToStepId` to be a primitive type in the JSON string but got " + data['subjectToStepId']);
        }

        return true;
    }


}



/**
 * @member {module:model/LocalisationLocalizedText} label
 */
ProductconfiguratorstepBulkCreateRequestCreateEntity.prototype['label'] = undefined;

/**
 * @member {module:model/LocalisationLocalizedText} description
 */
ProductconfiguratorstepBulkCreateRequestCreateEntity.prototype['description'] = undefined;

/**
 * @member {Boolean} isRequired
 */
ProductconfiguratorstepBulkCreateRequestCreateEntity.prototype['isRequired'] = undefined;

/**
 * @member {String} subjectToStepId
 */
ProductconfiguratorstepBulkCreateRequestCreateEntity.prototype['subjectToStepId'] = undefined;

/**
 * @member {Boolean} hasMultipleSelection
 */
ProductconfiguratorstepBulkCreateRequestCreateEntity.prototype['hasMultipleSelection'] = undefined;

/**
 * @member {Boolean} optionsHaveQuantity
 */
ProductconfiguratorstepBulkCreateRequestCreateEntity.prototype['optionsHaveQuantity'] = undefined;






export default ProductconfiguratorstepBulkCreateRequestCreateEntity;

