/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorconfiguratorStatus from './ProductconfiguratorconfiguratorStatus';

/**
 * The ProductconfiguratorconfiguratorUpdatePayload model module.
 * @module model/ProductconfiguratorconfiguratorUpdatePayload
 * @version v1
 */
class ProductconfiguratorconfiguratorUpdatePayload {
    /**
     * Constructs a new <code>ProductconfiguratorconfiguratorUpdatePayload</code>.
     * @alias module:model/ProductconfiguratorconfiguratorUpdatePayload
     */
    constructor() { 
        
        ProductconfiguratorconfiguratorUpdatePayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorconfiguratorUpdatePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorconfiguratorUpdatePayload} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorconfiguratorUpdatePayload} The populated <code>ProductconfiguratorconfiguratorUpdatePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorconfiguratorUpdatePayload();

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ProductconfiguratorconfiguratorStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorconfiguratorUpdatePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorconfiguratorUpdatePayload</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }

        return true;
    }


}



/**
 * @member {String} label
 */
ProductconfiguratorconfiguratorUpdatePayload.prototype['label'] = undefined;

/**
 * @member {module:model/ProductconfiguratorconfiguratorStatus} status
 */
ProductconfiguratorconfiguratorUpdatePayload.prototype['status'] = undefined;






export default ProductconfiguratorconfiguratorUpdatePayload;

