/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorpropertyUpdatePayload from './ProductconfiguratorpropertyUpdatePayload';

/**
 * The ProductconfiguratorpropertyUpdateRequest model module.
 * @module model/ProductconfiguratorpropertyUpdateRequest
 * @version v1
 */
class ProductconfiguratorpropertyUpdateRequest {
    /**
     * Constructs a new <code>ProductconfiguratorpropertyUpdateRequest</code>.
     * @alias module:model/ProductconfiguratorpropertyUpdateRequest
     */
    constructor() { 
        
        ProductconfiguratorpropertyUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorpropertyUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorpropertyUpdateRequest} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorpropertyUpdateRequest} The populated <code>ProductconfiguratorpropertyUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorpropertyUpdateRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('matrixId')) {
                obj['matrixId'] = ApiClient.convertToType(data['matrixId'], 'String');
            }
            if (data.hasOwnProperty('propertyId')) {
                obj['propertyId'] = ApiClient.convertToType(data['propertyId'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ProductconfiguratorpropertyUpdatePayload.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('payloadMask')) {
                obj['payloadMask'] = ApiClient.convertToType(data['payloadMask'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorpropertyUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorpropertyUpdateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['matrixId'] && !(typeof data['matrixId'] === 'string' || data['matrixId'] instanceof String)) {
            throw new Error("Expected the field `matrixId` to be a primitive type in the JSON string but got " + data['matrixId']);
        }
        // ensure the json data is a string
        if (data['propertyId'] && !(typeof data['propertyId'] === 'string' || data['propertyId'] instanceof String)) {
            throw new Error("Expected the field `propertyId` to be a primitive type in the JSON string but got " + data['propertyId']);
        }
        // validate the optional field `payload`
        if (data['payload']) { // data not null
          ProductconfiguratorpropertyUpdatePayload.validateJSON(data['payload']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['payloadMask'])) {
            throw new Error("Expected the field `payloadMask` to be an array in the JSON data but got " + data['payloadMask']);
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
ProductconfiguratorpropertyUpdateRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} matrixId
 */
ProductconfiguratorpropertyUpdateRequest.prototype['matrixId'] = undefined;

/**
 * @member {String} propertyId
 */
ProductconfiguratorpropertyUpdateRequest.prototype['propertyId'] = undefined;

/**
 * @member {module:model/ProductconfiguratorpropertyUpdatePayload} payload
 */
ProductconfiguratorpropertyUpdateRequest.prototype['payload'] = undefined;

/**
 * @member {Array.<String>} payloadMask
 */
ProductconfiguratorpropertyUpdateRequest.prototype['payloadMask'] = undefined;






export default ProductconfiguratorpropertyUpdateRequest;

