/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratoroptionUpdatePayload from './ProductconfiguratoroptionUpdatePayload';

/**
 * The ProductconfiguratoroptionUpdateRequest model module.
 * @module model/ProductconfiguratoroptionUpdateRequest
 * @version v1
 */
class ProductconfiguratoroptionUpdateRequest {
    /**
     * Constructs a new <code>ProductconfiguratoroptionUpdateRequest</code>.
     * @alias module:model/ProductconfiguratoroptionUpdateRequest
     */
    constructor() { 
        
        ProductconfiguratoroptionUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratoroptionUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratoroptionUpdateRequest} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratoroptionUpdateRequest} The populated <code>ProductconfiguratoroptionUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratoroptionUpdateRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('optionId')) {
                obj['optionId'] = ApiClient.convertToType(data['optionId'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ProductconfiguratoroptionUpdatePayload.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('payloadMask')) {
                obj['payloadMask'] = ApiClient.convertToType(data['payloadMask'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratoroptionUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratoroptionUpdateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['optionId'] && !(typeof data['optionId'] === 'string' || data['optionId'] instanceof String)) {
            throw new Error("Expected the field `optionId` to be a primitive type in the JSON string but got " + data['optionId']);
        }
        // validate the optional field `payload`
        if (data['payload']) { // data not null
          ProductconfiguratoroptionUpdatePayload.validateJSON(data['payload']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['payloadMask'])) {
            throw new Error("Expected the field `payloadMask` to be an array in the JSON data but got " + data['payloadMask']);
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
ProductconfiguratoroptionUpdateRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} optionId
 */
ProductconfiguratoroptionUpdateRequest.prototype['optionId'] = undefined;

/**
 * @member {module:model/ProductconfiguratoroptionUpdatePayload} payload
 */
ProductconfiguratoroptionUpdateRequest.prototype['payload'] = undefined;

/**
 * @member {Array.<String>} payloadMask
 */
ProductconfiguratoroptionUpdateRequest.prototype['payloadMask'] = undefined;






export default ProductconfiguratoroptionUpdateRequest;

