/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DependencyCondition from './DependencyCondition';

/**
 * The ProductconfiguratordependencyEntity model module.
 * @module model/ProductconfiguratordependencyEntity
 * @version v1
 */
class ProductconfiguratordependencyEntity {
    /**
     * Constructs a new <code>ProductconfiguratordependencyEntity</code>.
     * @alias module:model/ProductconfiguratordependencyEntity
     */
    constructor() { 
        
        ProductconfiguratordependencyEntity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratordependencyEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratordependencyEntity} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratordependencyEntity} The populated <code>ProductconfiguratordependencyEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratordependencyEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('grn')) {
                obj['grn'] = ApiClient.convertToType(data['grn'], 'String');
            }
            if (data.hasOwnProperty('optionIds')) {
                obj['optionIds'] = ApiClient.convertToType(data['optionIds'], ['String']);
            }
            if (data.hasOwnProperty('condition')) {
                obj['condition'] = DependencyCondition.constructFromObject(data['condition']);
            }
            if (data.hasOwnProperty('stepId')) {
                obj['stepId'] = ApiClient.convertToType(data['stepId'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratordependencyEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratordependencyEntity</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['grn'] && !(typeof data['grn'] === 'string' || data['grn'] instanceof String)) {
            throw new Error("Expected the field `grn` to be a primitive type in the JSON string but got " + data['grn']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['optionIds'])) {
            throw new Error("Expected the field `optionIds` to be an array in the JSON data but got " + data['optionIds']);
        }
        // validate the optional field `condition`
        if (data['condition']) { // data not null
          DependencyCondition.validateJSON(data['condition']);
        }
        // ensure the json data is a string
        if (data['stepId'] && !(typeof data['stepId'] === 'string' || data['stepId'] instanceof String)) {
            throw new Error("Expected the field `stepId` to be a primitive type in the JSON string but got " + data['stepId']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ProductconfiguratordependencyEntity.prototype['id'] = undefined;

/**
 * @member {String} grn
 */
ProductconfiguratordependencyEntity.prototype['grn'] = undefined;

/**
 * @member {Array.<String>} optionIds
 */
ProductconfiguratordependencyEntity.prototype['optionIds'] = undefined;

/**
 * @member {module:model/DependencyCondition} condition
 */
ProductconfiguratordependencyEntity.prototype['condition'] = undefined;

/**
 * @member {String} stepId
 */
ProductconfiguratordependencyEntity.prototype['stepId'] = undefined;

/**
 * @member {Date} createdAt
 */
ProductconfiguratordependencyEntity.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ProductconfiguratordependencyEntity.prototype['updatedAt'] = undefined;






export default ProductconfiguratordependencyEntity;

