/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductconfiguratoroptionCopyRequest model module.
 * @module model/ProductconfiguratoroptionCopyRequest
 * @version v1
 */
class ProductconfiguratoroptionCopyRequest {
    /**
     * Constructs a new <code>ProductconfiguratoroptionCopyRequest</code>.
     * @alias module:model/ProductconfiguratoroptionCopyRequest
     */
    constructor() { 
        
        ProductconfiguratoroptionCopyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratoroptionCopyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratoroptionCopyRequest} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratoroptionCopyRequest} The populated <code>ProductconfiguratoroptionCopyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratoroptionCopyRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('sourceOptionId')) {
                obj['sourceOptionId'] = ApiClient.convertToType(data['sourceOptionId'], 'String');
            }
            if (data.hasOwnProperty('targetStepId')) {
                obj['targetStepId'] = ApiClient.convertToType(data['targetStepId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratoroptionCopyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratoroptionCopyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['sourceOptionId'] && !(typeof data['sourceOptionId'] === 'string' || data['sourceOptionId'] instanceof String)) {
            throw new Error("Expected the field `sourceOptionId` to be a primitive type in the JSON string but got " + data['sourceOptionId']);
        }
        // ensure the json data is a string
        if (data['targetStepId'] && !(typeof data['targetStepId'] === 'string' || data['targetStepId'] instanceof String)) {
            throw new Error("Expected the field `targetStepId` to be a primitive type in the JSON string but got " + data['targetStepId']);
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
ProductconfiguratoroptionCopyRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} sourceOptionId
 */
ProductconfiguratoroptionCopyRequest.prototype['sourceOptionId'] = undefined;

/**
 * @member {String} targetStepId
 */
ProductconfiguratoroptionCopyRequest.prototype['targetStepId'] = undefined;






export default ProductconfiguratoroptionCopyRequest;

