/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorstepEntity from './ProductconfiguratorstepEntity';

/**
 * The ProductconfiguratorstepBulkCreateResponse model module.
 * @module model/ProductconfiguratorstepBulkCreateResponse
 * @version v1
 */
class ProductconfiguratorstepBulkCreateResponse {
    /**
     * Constructs a new <code>ProductconfiguratorstepBulkCreateResponse</code>.
     * @alias module:model/ProductconfiguratorstepBulkCreateResponse
     */
    constructor() { 
        
        ProductconfiguratorstepBulkCreateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorstepBulkCreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorstepBulkCreateResponse} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorstepBulkCreateResponse} The populated <code>ProductconfiguratorstepBulkCreateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorstepBulkCreateResponse();

            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [ProductconfiguratorstepEntity]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorstepBulkCreateResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorstepBulkCreateResponse</code>.
     */
    static validateJSON(data) {
        if (data['steps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['steps'])) {
                throw new Error("Expected the field `steps` to be an array in the JSON data but got " + data['steps']);
            }
            // validate the optional field `steps` (array)
            for (const item of data['steps']) {
                ProductconfiguratorstepEntity.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ProductconfiguratorstepEntity>} steps
 */
ProductconfiguratorstepBulkCreateResponse.prototype['steps'] = undefined;






export default ProductconfiguratorstepBulkCreateResponse;

