/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyUpdatePayloadGenericProperty from './PropertyUpdatePayloadGenericProperty';
import PropertyUpdatePayloadPriceProperty from './PropertyUpdatePayloadPriceProperty';
import PropertyUpdatePayloadWeightProperty from './PropertyUpdatePayloadWeightProperty';

/**
 * The ProductconfiguratorpropertyUpdatePayload model module.
 * @module model/ProductconfiguratorpropertyUpdatePayload
 * @version v1
 */
class ProductconfiguratorpropertyUpdatePayload {
    /**
     * Constructs a new <code>ProductconfiguratorpropertyUpdatePayload</code>.
     * @alias module:model/ProductconfiguratorpropertyUpdatePayload
     */
    constructor() { 
        
        ProductconfiguratorpropertyUpdatePayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorpropertyUpdatePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorpropertyUpdatePayload} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorpropertyUpdatePayload} The populated <code>ProductconfiguratorpropertyUpdatePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorpropertyUpdatePayload();

            if (data.hasOwnProperty('genericProperty')) {
                obj['genericProperty'] = PropertyUpdatePayloadGenericProperty.constructFromObject(data['genericProperty']);
            }
            if (data.hasOwnProperty('weightProperty')) {
                obj['weightProperty'] = PropertyUpdatePayloadWeightProperty.constructFromObject(data['weightProperty']);
            }
            if (data.hasOwnProperty('priceProperty')) {
                obj['priceProperty'] = PropertyUpdatePayloadPriceProperty.constructFromObject(data['priceProperty']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorpropertyUpdatePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorpropertyUpdatePayload</code>.
     */
    static validateJSON(data) {
        // validate the optional field `genericProperty`
        if (data['genericProperty']) { // data not null
          PropertyUpdatePayloadGenericProperty.validateJSON(data['genericProperty']);
        }
        // validate the optional field `weightProperty`
        if (data['weightProperty']) { // data not null
          PropertyUpdatePayloadWeightProperty.validateJSON(data['weightProperty']);
        }
        // validate the optional field `priceProperty`
        if (data['priceProperty']) { // data not null
          PropertyUpdatePayloadPriceProperty.validateJSON(data['priceProperty']);
        }

        return true;
    }


}



/**
 * @member {module:model/PropertyUpdatePayloadGenericProperty} genericProperty
 */
ProductconfiguratorpropertyUpdatePayload.prototype['genericProperty'] = undefined;

/**
 * @member {module:model/PropertyUpdatePayloadWeightProperty} weightProperty
 */
ProductconfiguratorpropertyUpdatePayload.prototype['weightProperty'] = undefined;

/**
 * @member {module:model/PropertyUpdatePayloadPriceProperty} priceProperty
 */
ProductconfiguratorpropertyUpdatePayload.prototype['priceProperty'] = undefined;






export default ProductconfiguratorpropertyUpdatePayload;

