/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorpropertyGenericProperty from './ProductconfiguratorpropertyGenericProperty';
import ProductconfiguratorpropertyPriceProperty from './ProductconfiguratorpropertyPriceProperty';
import ProductconfiguratorpropertyWeightProperty from './ProductconfiguratorpropertyWeightProperty';

/**
 * The ProductconfiguratorpropertyCreateRequest model module.
 * @module model/ProductconfiguratorpropertyCreateRequest
 * @version v1
 */
class ProductconfiguratorpropertyCreateRequest {
    /**
     * Constructs a new <code>ProductconfiguratorpropertyCreateRequest</code>.
     * @alias module:model/ProductconfiguratorpropertyCreateRequest
     */
    constructor() { 
        
        ProductconfiguratorpropertyCreateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorpropertyCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorpropertyCreateRequest} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorpropertyCreateRequest} The populated <code>ProductconfiguratorpropertyCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorpropertyCreateRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('matrixId')) {
                obj['matrixId'] = ApiClient.convertToType(data['matrixId'], 'String');
            }
            if (data.hasOwnProperty('stepIdToOptionId')) {
                obj['stepIdToOptionId'] = ApiClient.convertToType(data['stepIdToOptionId'], {'String': 'String'});
            }
            if (data.hasOwnProperty('genericProperty')) {
                obj['genericProperty'] = ProductconfiguratorpropertyGenericProperty.constructFromObject(data['genericProperty']);
            }
            if (data.hasOwnProperty('priceProperty')) {
                obj['priceProperty'] = ProductconfiguratorpropertyPriceProperty.constructFromObject(data['priceProperty']);
            }
            if (data.hasOwnProperty('weightProperty')) {
                obj['weightProperty'] = ProductconfiguratorpropertyWeightProperty.constructFromObject(data['weightProperty']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorpropertyCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorpropertyCreateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['matrixId'] && !(typeof data['matrixId'] === 'string' || data['matrixId'] instanceof String)) {
            throw new Error("Expected the field `matrixId` to be a primitive type in the JSON string but got " + data['matrixId']);
        }
        // validate the optional field `genericProperty`
        if (data['genericProperty']) { // data not null
          ProductconfiguratorpropertyGenericProperty.validateJSON(data['genericProperty']);
        }
        // validate the optional field `priceProperty`
        if (data['priceProperty']) { // data not null
          ProductconfiguratorpropertyPriceProperty.validateJSON(data['priceProperty']);
        }
        // validate the optional field `weightProperty`
        if (data['weightProperty']) { // data not null
          ProductconfiguratorpropertyWeightProperty.validateJSON(data['weightProperty']);
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
ProductconfiguratorpropertyCreateRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} matrixId
 */
ProductconfiguratorpropertyCreateRequest.prototype['matrixId'] = undefined;

/**
 * @member {Object.<String, String>} stepIdToOptionId
 */
ProductconfiguratorpropertyCreateRequest.prototype['stepIdToOptionId'] = undefined;

/**
 * @member {module:model/ProductconfiguratorpropertyGenericProperty} genericProperty
 */
ProductconfiguratorpropertyCreateRequest.prototype['genericProperty'] = undefined;

/**
 * @member {module:model/ProductconfiguratorpropertyPriceProperty} priceProperty
 */
ProductconfiguratorpropertyCreateRequest.prototype['priceProperty'] = undefined;

/**
 * @member {module:model/ProductconfiguratorpropertyWeightProperty} weightProperty
 */
ProductconfiguratorpropertyCreateRequest.prototype['weightProperty'] = undefined;






export default ProductconfiguratorpropertyCreateRequest;

