/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ProductconfiguratorPropertyMode.
* @enum {}
* @readonly
*/
export default class ProductconfiguratorPropertyMode {
    
        /**
         * value: "PROPERTY_MODE_UNKNOWN"
         * @const
         */
        "UNKNOWN" = "PROPERTY_MODE_UNKNOWN";

    
        /**
         * value: "PROPERTY_MODE_FINAL"
         * @const
         */
        "FINAL" = "PROPERTY_MODE_FINAL";

    
        /**
         * value: "PROPERTY_MODE_INCREMENTAL"
         * @const
         */
        "INCREMENTAL" = "PROPERTY_MODE_INCREMENTAL";

    

    /**
    * Returns a <code>ProductconfiguratorPropertyMode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ProductconfiguratorPropertyMode} The enum <code>ProductconfiguratorPropertyMode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

