/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LocalisationLocalizedText from './LocalisationLocalizedText';
import OptionSwatch from './OptionSwatch';

/**
 * The ProductconfiguratoroptionUpdatePayload model module.
 * @module model/ProductconfiguratoroptionUpdatePayload
 * @version v1
 */
class ProductconfiguratoroptionUpdatePayload {
    /**
     * Constructs a new <code>ProductconfiguratoroptionUpdatePayload</code>.
     * @alias module:model/ProductconfiguratoroptionUpdatePayload
     */
    constructor() { 
        
        ProductconfiguratoroptionUpdatePayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratoroptionUpdatePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratoroptionUpdatePayload} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratoroptionUpdatePayload} The populated <code>ProductconfiguratoroptionUpdatePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratoroptionUpdatePayload();

            if (data.hasOwnProperty('label')) {
                obj['label'] = LocalisationLocalizedText.constructFromObject(data['label']);
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
            if (data.hasOwnProperty('externalReferenceId')) {
                obj['externalReferenceId'] = ApiClient.convertToType(data['externalReferenceId'], 'String');
            }
            if (data.hasOwnProperty('swatch')) {
                obj['swatch'] = OptionSwatch.constructFromObject(data['swatch']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratoroptionUpdatePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratoroptionUpdatePayload</code>.
     */
    static validateJSON(data) {
        // validate the optional field `label`
        if (data['label']) { // data not null
          LocalisationLocalizedText.validateJSON(data['label']);
        }
        // ensure the json data is a string
        if (data['position'] && !(typeof data['position'] === 'string' || data['position'] instanceof String)) {
            throw new Error("Expected the field `position` to be a primitive type in the JSON string but got " + data['position']);
        }
        // ensure the json data is a string
        if (data['externalReferenceId'] && !(typeof data['externalReferenceId'] === 'string' || data['externalReferenceId'] instanceof String)) {
            throw new Error("Expected the field `externalReferenceId` to be a primitive type in the JSON string but got " + data['externalReferenceId']);
        }
        // validate the optional field `swatch`
        if (data['swatch']) { // data not null
          OptionSwatch.validateJSON(data['swatch']);
        }

        return true;
    }


}



/**
 * @member {module:model/LocalisationLocalizedText} label
 */
ProductconfiguratoroptionUpdatePayload.prototype['label'] = undefined;

/**
 * @member {String} position
 */
ProductconfiguratoroptionUpdatePayload.prototype['position'] = undefined;

/**
 * @member {String} externalReferenceId
 */
ProductconfiguratoroptionUpdatePayload.prototype['externalReferenceId'] = undefined;

/**
 * @member {module:model/OptionSwatch} swatch
 */
ProductconfiguratoroptionUpdatePayload.prototype['swatch'] = undefined;






export default ProductconfiguratoroptionUpdatePayload;

