/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductconfiguratorconfiguratorCopyRequest model module.
 * @module model/ProductconfiguratorconfiguratorCopyRequest
 * @version v1
 */
class ProductconfiguratorconfiguratorCopyRequest {
    /**
     * Constructs a new <code>ProductconfiguratorconfiguratorCopyRequest</code>.
     * @alias module:model/ProductconfiguratorconfiguratorCopyRequest
     */
    constructor() { 
        
        ProductconfiguratorconfiguratorCopyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductconfiguratorconfiguratorCopyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductconfiguratorconfiguratorCopyRequest} obj Optional instance to populate.
     * @return {module:model/ProductconfiguratorconfiguratorCopyRequest} The populated <code>ProductconfiguratorconfiguratorCopyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductconfiguratorconfiguratorCopyRequest();

            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('sourceConfiguratorId')) {
                obj['sourceConfiguratorId'] = ApiClient.convertToType(data['sourceConfiguratorId'], 'String');
            }
            if (data.hasOwnProperty('targetProductId')) {
                obj['targetProductId'] = ApiClient.convertToType(data['targetProductId'], 'String');
            }
            if (data.hasOwnProperty('copyDependencies')) {
                obj['copyDependencies'] = ApiClient.convertToType(data['copyDependencies'], 'Boolean');
            }
            if (data.hasOwnProperty('copyMatrices')) {
                obj['copyMatrices'] = ApiClient.convertToType(data['copyMatrices'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductconfiguratorconfiguratorCopyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductconfiguratorconfiguratorCopyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }
        // ensure the json data is a string
        if (data['sourceConfiguratorId'] && !(typeof data['sourceConfiguratorId'] === 'string' || data['sourceConfiguratorId'] instanceof String)) {
            throw new Error("Expected the field `sourceConfiguratorId` to be a primitive type in the JSON string but got " + data['sourceConfiguratorId']);
        }
        // ensure the json data is a string
        if (data['targetProductId'] && !(typeof data['targetProductId'] === 'string' || data['targetProductId'] instanceof String)) {
            throw new Error("Expected the field `targetProductId` to be a primitive type in the JSON string but got " + data['targetProductId']);
        }

        return true;
    }


}



/**
 * @member {String} tenantId
 */
ProductconfiguratorconfiguratorCopyRequest.prototype['tenantId'] = undefined;

/**
 * @member {String} sourceConfiguratorId
 */
ProductconfiguratorconfiguratorCopyRequest.prototype['sourceConfiguratorId'] = undefined;

/**
 * @member {String} targetProductId
 */
ProductconfiguratorconfiguratorCopyRequest.prototype['targetProductId'] = undefined;

/**
 * @member {Boolean} copyDependencies
 */
ProductconfiguratorconfiguratorCopyRequest.prototype['copyDependencies'] = undefined;

/**
 * @member {Boolean} copyMatrices
 */
ProductconfiguratorconfiguratorCopyRequest.prototype['copyMatrices'] = undefined;






export default ProductconfiguratorconfiguratorCopyRequest;

