/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ProductconfiguratorWeightUnit.
* @enum {}
* @readonly
*/
export default class ProductconfiguratorWeightUnit {
    
        /**
         * value: "WEIGHT_UNIT_UNKNOWN"
         * @const
         */
        "UNKNOWN" = "WEIGHT_UNIT_UNKNOWN";

    
        /**
         * value: "WEIGHT_UNIT_KILOGRAM"
         * @const
         */
        "KILOGRAM" = "WEIGHT_UNIT_KILOGRAM";

    
        /**
         * value: "WEIGHT_UNIT_POUND"
         * @const
         */
        "POUND" = "WEIGHT_UNIT_POUND";

    

    /**
    * Returns a <code>ProductconfiguratorWeightUnit</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ProductconfiguratorWeightUnit} The enum <code>ProductconfiguratorWeightUnit</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

