/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertyUpdatePayloadGenericProperty model module.
 * @module model/PropertyUpdatePayloadGenericProperty
 * @version v1
 */
class PropertyUpdatePayloadGenericProperty {
    /**
     * Constructs a new <code>PropertyUpdatePayloadGenericProperty</code>.
     * @alias module:model/PropertyUpdatePayloadGenericProperty
     */
    constructor() { 
        
        PropertyUpdatePayloadGenericProperty.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyUpdatePayloadGenericProperty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyUpdatePayloadGenericProperty} obj Optional instance to populate.
     * @return {module:model/PropertyUpdatePayloadGenericProperty} The populated <code>PropertyUpdatePayloadGenericProperty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyUpdatePayloadGenericProperty();

            if (data.hasOwnProperty('propertyValue')) {
                obj['propertyValue'] = ApiClient.convertToType(data['propertyValue'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertyUpdatePayloadGenericProperty</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertyUpdatePayloadGenericProperty</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['propertyValue'] && !(typeof data['propertyValue'] === 'string' || data['propertyValue'] instanceof String)) {
            throw new Error("Expected the field `propertyValue` to be a primitive type in the JSON string but got " + data['propertyValue']);
        }

        return true;
    }


}



/**
 * @member {String} propertyValue
 */
PropertyUpdatePayloadGenericProperty.prototype['propertyValue'] = undefined;






export default PropertyUpdatePayloadGenericProperty;

