/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductconfiguratorpropertyEntity from './ProductconfiguratorpropertyEntity';

/**
 * The PropertyListPropertiesResponse model module.
 * @module model/PropertyListPropertiesResponse
 * @version v1
 */
class PropertyListPropertiesResponse {
    /**
     * Constructs a new <code>PropertyListPropertiesResponse</code>.
     * @alias module:model/PropertyListPropertiesResponse
     */
    constructor() { 
        
        PropertyListPropertiesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyListPropertiesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyListPropertiesResponse} obj Optional instance to populate.
     * @return {module:model/PropertyListPropertiesResponse} The populated <code>PropertyListPropertiesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyListPropertiesResponse();

            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [ProductconfiguratorpropertyEntity]);
            }
            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertyListPropertiesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertyListPropertiesResponse</code>.
     */
    static validateJSON(data) {
        if (data['properties']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['properties'])) {
                throw new Error("Expected the field `properties` to be an array in the JSON data but got " + data['properties']);
            }
            // validate the optional field `properties` (array)
            for (const item of data['properties']) {
                ProductconfiguratorpropertyEntity.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['nextPageToken'] && !(typeof data['nextPageToken'] === 'string' || data['nextPageToken'] instanceof String)) {
            throw new Error("Expected the field `nextPageToken` to be a primitive type in the JSON string but got " + data['nextPageToken']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ProductconfiguratorpropertyEntity>} properties
 */
PropertyListPropertiesResponse.prototype['properties'] = undefined;

/**
 * @member {String} nextPageToken
 */
PropertyListPropertiesResponse.prototype['nextPageToken'] = undefined;






export default PropertyListPropertiesResponse;

