/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProductConfiguratorService);
  }
}(this, function(expect, ProductConfiguratorService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProductConfiguratorService.ConfigurationProperty();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigurationProperty', function() {
    it('should create an instance of ConfigurationProperty', function() {
      // uncomment below and update the code to test ConfigurationProperty
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be.a(ProductConfiguratorService.ConfigurationProperty);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

    it('should have the property grn (base name: "grn")', function() {
      // uncomment below and update the code to test the property grn
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

    it('should have the property optionIds (base name: "optionIds")', function() {
      // uncomment below and update the code to test the property optionIds
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

    it('should have the property propertyKey (base name: "propertyKey")', function() {
      // uncomment below and update the code to test the property propertyKey
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

    it('should have the property propertyValue (base name: "propertyValue")', function() {
      // uncomment below and update the code to test the property propertyValue
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

    it('should have the property propertyType (base name: "propertyType")', function() {
      // uncomment below and update the code to test the property propertyType
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

    it('should have the property propertyMode (base name: "propertyMode")', function() {
      // uncomment below and update the code to test the property propertyMode
      //var instance = new ProductConfiguratorService.ConfigurationProperty();
      //expect(instance).to.be();
    });

  });

}));
