/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProductConfiguratorService);
  }
}(this, function(expect, ProductConfiguratorService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProductConfiguratorService.MatrixListMatricesResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MatrixListMatricesResponse', function() {
    it('should create an instance of MatrixListMatricesResponse', function() {
      // uncomment below and update the code to test MatrixListMatricesResponse
      //var instance = new ProductConfiguratorService.MatrixListMatricesResponse();
      //expect(instance).to.be.a(ProductConfiguratorService.MatrixListMatricesResponse);
    });

    it('should have the property matrices (base name: "matrices")', function() {
      // uncomment below and update the code to test the property matrices
      //var instance = new ProductConfiguratorService.MatrixListMatricesResponse();
      //expect(instance).to.be();
    });

    it('should have the property nextPageToken (base name: "nextPageToken")', function() {
      // uncomment below and update the code to test the property nextPageToken
      //var instance = new ProductConfiguratorService.MatrixListMatricesResponse();
      //expect(instance).to.be();
    });

  });

}));
