/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProductConfiguratorService);
  }
}(this, function(expect, ProductConfiguratorService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductconfiguratormatrixEntity', function() {
    it('should create an instance of ProductconfiguratormatrixEntity', function() {
      // uncomment below and update the code to test ProductconfiguratormatrixEntity
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be.a(ProductConfiguratorService.ProductconfiguratormatrixEntity);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property grn (base name: "grn")', function() {
      // uncomment below and update the code to test the property grn
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property configuratorId (base name: "configuratorId")', function() {
      // uncomment below and update the code to test the property configuratorId
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property defaultPropertyId (base name: "defaultPropertyId")', function() {
      // uncomment below and update the code to test the property defaultPropertyId
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property propertiesMode (base name: "propertiesMode")', function() {
      // uncomment below and update the code to test the property propertiesMode
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property genericType (base name: "genericType")', function() {
      // uncomment below and update the code to test the property genericType
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property priceType (base name: "priceType")', function() {
      // uncomment below and update the code to test the property priceType
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property weightType (base name: "weightType")', function() {
      // uncomment below and update the code to test the property weightType
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property steps (base name: "steps")', function() {
      // uncomment below and update the code to test the property steps
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProductConfiguratorService.ProductconfiguratormatrixEntity();
      //expect(instance).to.be();
    });

  });

}));
