/**
 * Product Configurator Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProductConfiguratorService);
  }
}(this, function(expect, ProductConfiguratorService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductconfiguratorstepEntity', function() {
    it('should create an instance of ProductconfiguratorstepEntity', function() {
      // uncomment below and update the code to test ProductconfiguratorstepEntity
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be.a(ProductConfiguratorService.ProductconfiguratorstepEntity);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property grn (base name: "grn")', function() {
      // uncomment below and update the code to test the property grn
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property subjectToStepId (base name: "subjectToStepId")', function() {
      // uncomment below and update the code to test the property subjectToStepId
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property isRequired (base name: "isRequired")', function() {
      // uncomment below and update the code to test the property isRequired
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property hasMultipleSelection (base name: "hasMultipleSelection")', function() {
      // uncomment below and update the code to test the property hasMultipleSelection
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property optionsHaveQuantity (base name: "optionsHaveQuantity")', function() {
      // uncomment below and update the code to test the property optionsHaveQuantity
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProductConfiguratorService.ProductconfiguratorstepEntity();
      //expect(instance).to.be();
    });

  });

}));
